### ISSUE TITLE
Bad Request 

### ISSUE THREAD

**Issue by ion05** [ion05/browser#1]
Upon running the code , I get a bad request error 

`HTTP/1.1 400 Bad Request
Date: Fri, 31 Jul 2020 06:22:54 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 308
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at do1.dr-chuck.com Port 80</address>
</body></html>`

**Comment by dotrachit** [comment]
https://www.py4e.com/code3/socket1.py

**Comment by ion05** [comment]
Ok thanx @dotrachit
